"""Compare IKP knowledge fingerprints with single-token fingerprints.

The two instruments observe different black-box channels: IKP records which
rare facts a model knows (and which wrong answers it shares), whereas the
single-token instrument records distributions over repeated trivial answers.
This module aligns their pairwise data without collapsing reasoning variants
onto non-reasoning endpoints.
"""

from __future__ import annotations

import csv

from scipy.stats import spearmanr


def read_distance_matrix(source):
    """Read a symmetric wide CSV and retain each unordered pair once."""
    reader = csv.reader(source)
    header = next(reader)
    models = header[1:]
    distances = {}
    for row in reader:
        model_a = row[0]
        for model_b, value in zip(models, row[1:]):
            if model_a < model_b:
                distances[(model_a, model_b)] = float(value)
    return distances


def _is_thinking_variant(name: str) -> bool:
    normalized = name.lower().replace("_", "-")
    return "think" in normalized or "reasoning" in normalized


def align_fingerprint_pairs(knowledge_pairs, model_ids, distances):
    """Join pairwise IKP metrics to exact single-token model identifiers."""
    aligned = []
    for pair_key, metrics in knowledge_pairs.items():
        short_a, short_b = pair_key.split("||", 1)
        if _is_thinking_variant(short_a) or _is_thinking_variant(short_b):
            continue
        model_a = model_ids.get(short_a)
        model_b = model_ids.get(short_b)
        if not model_a or not model_b or model_a == model_b:
            continue
        pair = tuple(sorted((model_a, model_b)))
        if pair not in distances:
            continue
        aligned.append({
            "model_a": pair[0],
            "model_b": pair[1],
            "jsd": distances[pair],
            "jaccard": metrics["jaccard"],
            "hss": metrics["hss"],
            "lift": metrics["lift"],
            "both_wrong": metrics["both_wrong"],
        })
    return aligned


def _correlation(rows, metric):
    if len(rows) < 2:
        return {"n": len(rows), "spearman_rho": None}
    result = spearmanr([-row["jsd"] for row in rows], [row[metric] for row in rows])
    return {"n": len(rows), "spearman_rho": round(float(result.statistic), 3)}


def summarize_alignment(aligned, min_joint_wrong=10):
    """Return descriptive correlations for all, within-, and cross-vendor pairs."""
    groups = {
        "all": aligned,
        "same_vendor": [
            row for row in aligned
            if row["model_a"].split("/", 1)[0] == row["model_b"].split("/", 1)[0]
        ],
        "cross_vendor": [
            row for row in aligned
            if row["model_a"].split("/", 1)[0] != row["model_b"].split("/", 1)[0]
        ],
    }
    correlations = {}
    for group_name, rows in groups.items():
        hss_rows = [row for row in rows if row["both_wrong"] >= min_joint_wrong]
        correlations[group_name] = {
            "jaccard": _correlation(rows, "jaccard"),
            "hss": _correlation(hss_rows, "hss"),
        }
    models = {row[key] for row in aligned for key in ("model_a", "model_b")}
    return {
        "n_models": len(models),
        "n_pairs": len(aligned),
        "min_joint_wrong_for_hss": min_joint_wrong,
        "correlations": correlations,
    }


def render_latex_table(summary):
    """Render the descriptive correlations as a compact LaTeX table."""
    labels = {
        "all": "All pairs",
        "same_vendor": "Same vendor",
        "cross_vendor": "Cross vendor",
    }
    metric_labels = {"jaccard": "Jaccard", "hss": "HSS"}
    rows = []
    for group in ("all", "same_vendor", "cross_vendor"):
        for metric in ("jaccard", "hss"):
            result = summary["correlations"][group][metric]
            rho = "---" if result["spearman_rho"] is None else f'{result["spearman_rho"]:.3f}'
            rows.append(
                f'{labels[group]} & {metric_labels[metric]} & {result["n"]} & {rho} \\\\'
            )
    body = "\n".join(rows)
    return f"""% Generated by scripts/20_single_token_complementarity.py.
\\begin{{table}}[H]
    \\centering
    \\small
    \\begin{{tabular}}{{llrr}}
        \\toprule
        Pair subset & IKP metric & $n$ pairs & Spearman $\\rho$ \\\\
        \\midrule
{body}
        \\bottomrule
    \\end{{tabular}}
    \\caption{{Descriptive rank correlation between single-token behavioral similarity ($-\\mathrm{{JSD}}$) and IKP knowledge-fingerprint similarity. HSS rows require at least ten probes on which both models are wrong. Pairwise observations share models and are therefore not independent; the correlations quantify overlap between signals rather than inferential significance.}}
    \\label{{tab:single-token-complementarity}}
\\end{{table}}
"""
